export const TRACKS = {
  finance: { label: "금융·AI", shortLabel: "금융·AI", description: "투자리서치, 금융 데이터, 리스크·준법, AI 제품까지 폭넓게 열어둡니다." },
  backoffice: { label: "백오피스 전반", shortLabel: "백오피스", description: "손익·KPI·프로세스·보고·자동화를 한 사례로 묶는 트랙입니다." },
  strategy: { label: "경영전략·기획", shortLabel: "경영전략", description: "과제 발굴, 타당성, 효과 추정, 로드맵과 경영진 보고 역량을 봅니다." },
  accounting: { label: "재무기획·회계", shortLabel: "재무·회계", description: "예산·손익·운전자본·관리회계와 수치 정확성을 중심으로 봅니다." },
  hr: { label: "인사·총무", shortLabel: "인사·총무", description: "문서·마스터데이터 표준화, 승인·권한, 온보딩과 운영 자동화에 초점을 둡니다." },
};

const briefing = (details) => ({ sessionDate: "2026-10-02", ...details });

export const capstones = [
  {
    id: "donghoon", company: "동훈인베스트먼트", title: "VC/PE 리서치·규정검증 AI Agent",
    scores: { finance: 94, backoffice: 74, strategy: 80, accounting: 61, hr: 55 },
    keywords: ["VC/PE", "투자심사", "RAG", "컴플라이언스", "사람 검증"],
    strength: "금융 도메인, 실무진 밀착 멘토링, 채용 가능성과 결과물 활용성이 함께 확인됐습니다.",
    caution: "소규모 조직인 만큼 역할이 넓습니다. 리서치와 규정검증 중 핵심 KPI를 먼저 좁혀야 합니다.",
    briefing: briefing({
      stage: "실무 고도화", stageLevel: "live",
      scope: "투자검토·산업/피어 분석과 내부 규정·계약서 매칭을 자동화하고, 최종 판단은 사람이 검증하는 흐름입니다.",
      data: "내부 투자자료와 공개자료를 함께 사용합니다. 크롤링·분류·근거 추적 품질이 핵심입니다.",
      mentoring: "선릉 사무실에서 투자팀 리더와 가깝게 일하며 IR·투자심의 등 실제 업무를 볼 기회가 있습니다.",
      workstyle: "최소 2명, 현장 중심·9–6 탄력 운영. 유료 LLM 비용은 월 최대 500달러 수준까지 지원 의사를 밝혔습니다.",
      portfolio: "결과물 활용 가능", portfolioLevel: "good",
      portfolioDetail: "민감 원문은 제외해야 하지만 UI·대시보드·결과물은 개인 활용이 가능하다고 설명했습니다.",
      hiring: "우선 면접 가능", hiringLevel: "good",
      hiringDetail: "현재 인턴·채용 수요가 있고, 성과가 좋으면 투자 애널리스트 직무 우선 면접이나 계열사 추천 가능성을 언급했습니다.",
      risk: "AI 엔지니어보다 ‘AI를 활용하는 투자 애널리스트’에 가까운 역할입니다.",
    }),
  },
  {
    id: "kyobo", company: "교보증권", title: "기업가치평가 방법론 추천 플랫폼",
    scores: { finance: 88, backoffice: 63, strategy: 76, accounting: 74, hr: 48 },
    keywords: ["밸류에이션", "DCF", "SOTP", "기업분석", "근거 설명"],
    strength: "증권사 애널리스트의 암묵지를 구조화해 리서치·밸류에이션 직무를 직접 경험합니다.",
    caution: "채용 연계는 없고 데이터 라이선스와 외부 반출, 정답셋·평가 기준이 아직 불확실합니다.",
    briefing: briefing({
      stage: "신규 PoC", stageLevel: "pilot",
      scope: "기업·산업 특성을 읽고 PBR·PER·DCF·SOTP 등 가치평가 방법론을 추천한 뒤 근거를 설명하는 3단계 시스템입니다.",
      data: "재무데이터와 실제 분석 사례를 제공할 예정이지만 FnGuide·QuantWise·Bloomberg 사용 권한은 추가 확인이 필요합니다.",
      mentoring: "리서치센터 애널리스트가 주 1–2회 피드백합니다. 바쁜 시즌에는 학생이 질문을 구조화해 먼저 요청해야 합니다.",
      workstyle: "리서치센터 좌석은 현재 여유가 적고 12월 이전 계획 이후 변동 가능성이 있습니다. 식대 지원은 없습니다.",
      portfolio: "반출 협의 필요", portfolioLevel: "warn",
      portfolioDetail: "내·외부망과 유료 데이터 라이선스 때문에 재현 가능한 공개 버전은 별도 샘플 데이터로 다시 만들어야 합니다.",
      hiring: "직접 연계 없음", hiringLevel: "bad",
      hiringDetail: "금융회사 공개채용·공정채용 원칙상 캡스톤을 인턴·정규직으로 직접 연결하기 어렵다고 명확히 설명했습니다.",
      risk: "‘좋은 추천’의 정답과 성능평가 방식을 초기에 합의하지 않으면 데모 수준에 머물 수 있습니다.",
    }),
  },
  {
    id: "anda", company: "안다아시아벤처스", title: "벤처투자·펀드관리 AI Agent",
    scores: { finance: 86, backoffice: 72, strategy: 79, accounting: 62, hr: 54 },
    keywords: ["VC/PE", "IR 스크리닝", "펀드레이징", "RAG", "대시보드"],
    strength: "VC 현장에서 펀드공고·펀드레이징·IR 스크리닝 제품을 실사용 수준으로 고도화합니다.",
    caution: "회사 원본 DB와 프로젝트는 반출할 수 없고, 기술 멘토보다 도메인 멘토 비중이 높습니다.",
    briefing: briefing({
      stage: "사내 프로토타입 고도화", stageLevel: "live",
      scope: "모태펀드 공고, 펀드레이징, 초기 딜·IR 스크리닝의 세 모듈을 기존 초안에서 실사용 제품으로 발전시킵니다.",
      data: "고객 개인정보 등 극민감 정보를 제외한 내부자료를 보안서약 하에 제공합니다.",
      mentoring: "회사에 상주하며 수시로 도메인 피드백을 받고 최소 주 1회 리뷰합니다. 기술 지원은 교수·조교와 기존 인턴 의존도가 있습니다.",
      workstyle: "약 12명 규모 조직에서 프로젝트별로 1명이 맡을 가능성이 큽니다. 식대 지원이 있습니다.",
      portfolio: "원본 반출 불가", portfolioLevel: "bad",
      portfolioDetail: "회사 DB와 프로젝트 자체는 가져갈 수 없다고 설명했습니다. 공개용 재구축 범위를 시작 전에 서면 합의해야 합니다.",
      hiring: "신입 1명 검토", hiringLevel: "good",
      hiringDetail: "내년 신입 약 1명 채용 계획을 언급했고, 3개월 동안 핏을 확인할 수 있으나 채용 보장은 아닙니다.",
      risk: "한 사람이 한 모듈을 전담하면 개발 병목이 생길 수 있어 공통 인프라와 코드리뷰 체계가 필요합니다.",
    }),
  },
  {
    id: "car-operations", company: "CAR123JASPER", title: "차량운영 분석자산 통합·검증",
    scores: { finance: 72, backoffice: 88, strategy: 84, accounting: 72, hr: 76 },
    keywords: ["데이터 품질", "지표사전", "운영 KPI", "Text-to-SQL", "수익 검증"],
    strength: "흩어진 운영 도구를 표준화하고 데이터 정확성과 실제 수익 효과를 함께 검증할 수 있습니다.",
    caution: "기존 도구 7개를 모두 통합하려 하면 범위가 큽니다. 핵심 의사결정 1–2개를 우선해야 합니다.",
    briefing: briefing({
      stage: "운영 도구 통합", stageLevel: "live",
      scope: "차량 약 1,450대의 정비·주차수요·재배치·정산 관련 기존 분석도구를 한 플랫폼으로 통합하고 검증합니다.",
      data: "실제 차량 운영 데이터 수천~수만 건과 서로 다른 사내 포맷을 표준화합니다.",
      mentoring: "현재 도구를 직접 만든 실무자와 사용자 피드백을 받을 수 있습니다. 구체적인 정기 멘토링 주기는 미정입니다.",
      workstyle: "입찰지원 프로젝트와 별도 팀 구성을 선호하며 인원·클라우드 자원은 학생이 제안하기를 기대합니다.",
      portfolio: "공개 범위 미정", portfolioLevel: "warn",
      portfolioDetail: "운영 데이터 마스킹과 회사 승인 조건을 확인해야 합니다. 지표사전·아키텍처·합성데이터 데모가 안전한 공개안입니다.",
      hiring: "언급 없음", hiringLevel: "neutral",
      hiringDetail: "설명회에서 인턴·정규직 채용 연계나 수료증 조건은 구체적으로 언급되지 않았습니다.",
      risk: "정확도 개선뿐 아니라 정비비·가동률·재배치 비용 등 사업 KPI를 베이스라인과 비교해야 합니다.",
    }),
  },
  {
    id: "car-bidding", company: "CAR123JASPER", title: "조달청 차량임차 입찰지원",
    scores: { finance: 80, backoffice: 79, strategy: 84, accounting: 75, hr: 57 },
    keywords: ["문서 파싱", "입찰 의사결정", "가격구간", "백테스트", "수요예측"],
    strength: "비정형 공고를 가격·수요 의사결정으로 연결해 정량적 업무효과를 보여주기 좋습니다.",
    caution: "경쟁사 과거 투찰 데이터가 부족해 낙찰확률·가격예측의 상한을 현실적으로 설정해야 합니다.",
    briefing: briefing({
      stage: "현업 자동화", stageLevel: "live",
      scope: "형식이 제각각인 나라장터 공고를 표준 필드로 추출하고 입찰 여부·가격 범위·향후 차량수요를 지원합니다.",
      data: "공고 약 1,800건, 실제 입찰 약 152건을 보유했다고 설명했습니다. 경쟁사 투찰 이력은 제한적입니다.",
      mentoring: "실제 수작업을 하는 견적·운영 담당자의 검증을 받을 수 있으나 멘토링 주기는 추가 합의가 필요합니다.",
      workstyle: "운영분석 프로젝트와 별도 팀을 선호합니다. 민감 문서는 마스킹 후 일반 AI 도구를 사용할 수 있습니다.",
      portfolio: "공개 범위 미정", portfolioLevel: "warn",
      portfolioDetail: "문서 원문 대신 스키마·파서·합성 공고·백테스트 방법을 중심으로 공개하는 편이 안전합니다.",
      hiring: "언급 없음", hiringLevel: "neutral",
      hiringDetail: "설명회에서 직접적인 채용 연계 조건은 확인되지 않았습니다.",
      risk: "회사 제시 목표 승률은 보장값이 아닙니다. 파싱시간 단축과 의사결정 일관성을 1차 KPI로 잡아야 합니다.",
    }),
  },
  {
    id: "government-data", company: "국가데이터처", title: "AI 기반 국가데이터 표준변환",
    scores: { finance: 63, backoffice: 83, strategy: 75, accounting: 61, hr: 86 },
    keywords: ["주소 표준화", "행정서식", "마스터데이터", "공공 API", "데이터 품질"],
    strength: "행정 문서·주소·분류체계를 표준화해 인사·총무의 마스터데이터와 운영 혁신으로 연결하기 좋습니다.",
    caution: "대전 실무진과 원격 협업 비중이 높고 API 예산과 결과물의 실제 운영 반영 가능성이 불확실합니다.",
    briefing: briefing({
      stage: "기존 방식 재검증·확장", stageLevel: "pilot",
      scope: "주소 표준화, 행정서식 DB 자동화, 여력이 있으면 범용 표준변환까지 한 팀이 순차적으로 수행합니다.",
      data: "비민감·공개 데이터를 중심으로 LLM, 지오코딩·공간조인, 공공 API, 문서 항목 추출을 사용합니다.",
      mentoring: "학생은 학동 인근 나라셈도서관에서 근무하고 담당자는 대전에 있어 원격 관리가 중심입니다. 주 1–2회 대면을 계획했습니다.",
      workstyle: "4명이 같은 과제를 순차 수행할 가능성이 큽니다. 로컬 GPU보다 API를 쓰며 호출비 예산을 먼저 확정해야 합니다.",
      portfolio: "공개형 구성 가능", portfolioLevel: "good",
      portfolioDetail: "비민감·공개 데이터 비중이 높아 재현성은 좋지만 기관명·내부 평가수치 공개는 승인받아야 합니다.",
      hiring: "공공기관 경험", hiringLevel: "neutral",
      hiringDetail: "직접 채용 연계보다 세미나·포럼과 공공 데이터 거버넌스 경험이 주요 이점으로 제시됐습니다.",
      risk: "이전 기수 산출물이 바로 운영에 쓰이지 않았다는 설명이 있어 사용자·배포 책임자를 초기에 특정해야 합니다.",
    }),
  },
  {
    id: "aurora-demand", company: "오로라월드", title: "글로벌 수요예측·운전자본 최적화",
    scores: { finance: 71, backoffice: 91, strategy: 89, accounting: 95, hr: 65 },
    keywords: ["수요예측", "재고", "운전자본", "글로벌 협업", "비용 검증"],
    strength: "실제 글로벌 판매·재고 데이터로 FP&A·관리회계·운전자본 개선을 가장 직접적으로 증명합니다.",
    caution: "미국팀 정기회의가 오전 8시에 열릴 수 있고, 지원 혜택·공개 범위는 아직 확정되지 않았습니다.",
    briefing: briefing({
      stage: "운영 프로젝트 고도화", stageLevel: "live",
      scope: "약 3,000개 활성 품목의 수요 패턴을 재검증하고 예측·재고 최적화가 비용에 미치는 효과를 측정합니다.",
      data: "미국·영국·독일·홍콩 법인의 판매, 재고, 품목 마스터와 업무 프로세스를 제공합니다.",
      mentoring: "사내 현업과 미국팀이 참여하며 기존 3×3 군집·9개 패턴의 타당성을 함께 검증합니다.",
      workstyle: "프로젝트당 최소 3명 정도를 선호합니다. 미국팀 회의는 시차 때문에 오전 8시가 될 수 있습니다.",
      portfolio: "승인 범위 확인", portfolioLevel: "warn",
      portfolioDetail: "글로벌 판매·재고 원문 대신 익명화 스키마, 예측 검증법, 비용 시뮬레이션을 공개 산출물로 합의해야 합니다.",
      hiring: "언급 없음", hiringLevel: "neutral",
      hiringDetail: "설명회에서 직접 채용 연계와 별도 복지는 확정해 말하지 않았습니다.",
      risk: "예측오차만 보지 말고 결품·재고회전·현금전환주기 개선으로 연결해야 회계·FP&A 포트폴리오가 됩니다.",
    }),
  },
  {
    id: "yujin", company: "유진한일합섬", title: "영업·생산·수익성 최적화",
    scores: { finance: 70, backoffice: 96, strategy: 96, accounting: 94, hr: 78 },
    keywords: ["마진", "재고", "생산계획", "전사 KPI", "CEO 스폰서십"],
    strength: "CEO·전략기획 조직과 실데이터로 영업–생산–손익 의사결정을 연결해 경영전략 포트폴리오를 만들 수 있습니다.",
    caution: "수익성 최적화와 비전 불량검출까지 범위가 넓어 3개월 핵심 산출물을 명확히 잘라야 합니다.",
    briefing: briefing({
      stage: "운영 프로젝트 2단계", stageLevel: "live",
      scope: "기존 영업·생산·수익성 최적화의 2단계를 완성하고, 여력에 따라 정상 이미지 기반 불량 탐지까지 확장합니다.",
      data: "ERP의 과거 판매·생산·작업지시 데이터를 활용해 고객등급, 생산일정, 가동중단, 마진을 연결합니다.",
      mentoring: "CEO가 직접 후원하고 전략·기획 조직에 배치됩니다. 생산·영업·재무 도메인 담당자와 외부 비전 전문가도 참여합니다.",
      workstyle: "공덕 본사 근무, 월 1–2회 CEO 미팅·식사, 인턴 증명서와 AWS·모델 자원·활동비 지원을 제시했습니다.",
      portfolio: "재구성 협의", portfolioLevel: "warn",
      portfolioDetail: "실제 ERP 원문은 제외하고 KPI 정의서·최적화 구조·합성데이터 대시보드를 남기는 조건을 서면 합의해야 합니다.",
      hiring: "성장 경로 가능", hiringLevel: "good",
      hiringDetail: "그룹 AI 조직과 이전 기수 채용 사례를 언급했지만 이번 기수 채용을 보장한 것은 아닙니다.",
      risk: "회사가 제시한 마진·재고 목표치는 기대치입니다. 기준선, 제약조건, 실제 반영 가능한 KPI를 다시 합의해야 합니다.",
    }),
  },
  {
    id: "kpmg", company: "KPMG", title: "기업 데이터 중심 AX 전략",
    scores: { finance: 72, backoffice: 86, strategy: 90, accounting: 69, hr: 80 },
    keywords: ["AX 전략", "과제 발굴", "PoC", "거버넌스", "로드맵"],
    strength: "현황진단부터 AX 과제·PoC·거버넌스·로드맵까지 컨설팅의 전체 흐름을 경험합니다.",
    caution: "LIG D&A 제안은 수주 확정 전이고, 방산 보안 때문에 결과물을 개인 포트폴리오로 보유하기 어렵습니다.",
    briefing: briefing({
      stage: "고객 제안·수주 전", stageLevel: "proposal",
      scope: "LIG D&A 데이터 인프라를 진단하고 AX 과제를 우선순위화해 PoC, 목표 아키텍처, 거버넌스, 실행 로드맵을 제시합니다.",
      data: "방산 민감데이터와 폐쇄망·온프레미스 환경이 예상됩니다. 수주 실패 시 수협은행 AI 거버넌스 등 다른 과제로 바뀔 수 있습니다.",
      mentoring: "KDT 출신 컨설턴트와 실무 컨설턴트가 멘토링하며 실제 컨설팅 산출물 작성 방식을 배울 수 있습니다.",
      workstyle: "근무지는 고객사 용인 또는 KPMG 본사로 확정 전입니다. 인턴 활동증명과 식대 지원을 제시했습니다.",
      portfolio: "결과물 보유 불가", portfolioLevel: "bad",
      portfolioDetail: "익명화하더라도 고객 결과물을 개인이 소장하기 어렵다고 설명했습니다. 배운 방법론으로 외부 사례를 새로 만들어야 합니다.",
      hiring: "채용 사례 다수", hiringLevel: "good",
      hiringDetail: "과거 캡스톤 참여자 6명이 입사했고 최근 기수에서도 2명이 채용됐다고 설명했습니다. 이번 채용 보장은 아닙니다.",
      risk: "프로젝트 주제·근무지·데이터 접근이 바뀔 수 있어 최종 배정 전 확인해야 합니다.",
    }),
  },
  {
    id: "kt-alpha", company: "KT알파", title: "홈쇼핑 외부변수 영향도 분석",
    scores: { finance: 67, backoffice: 87, strategy: 90, accounting: 82, hr: 66 },
    keywords: ["방송 편성", "외부변수", "기여도", "What-if", "업무 적용"],
    strength: "실제 편성 의사결정에서 날씨·휴일·경쟁사·인접 프로그램의 영향을 검증하고 운영 적용까지 연결합니다.",
    caution: "별도의 해외벤더 편성 AI와 역할이 겹치지 않게 외부변수 가설과 평가 범위를 명확히 해야 합니다.",
    briefing: briefing({
      stage: "실운영 분석", stageLevel: "live",
      scope: "홈쇼핑 편성에서 외부 요인의 매출 영향을 분석하고 예측·What-if 기능이 있는 간단한 웹 프로토타입을 만듭니다.",
      data: "개인정보를 제거한 주문·고객군·방송·프로모션·할인·성과 데이터와 날씨·휴일·경쟁사 편성 등을 결합합니다.",
      mentoring: "사내 현업과 가까이 일하며 범위·가설을 협의하고, 프로젝트 이후 실제 적용 피드백까지 제공하겠다고 설명했습니다.",
      workstyle: "현장 중심, 약 4명 이상적·최대 5명. 식대 지원과 필요 AI 비용 협의를 제시했습니다.",
      portfolio: "사전 승인 필요", portfolioLevel: "warn",
      portfolioDetail: "대외 발표·포트폴리오 사용은 회사 사전 승인이 필요합니다. 재현 가능한 코드·보고서·샘플 웹을 계약 초기에 정의해야 합니다.",
      hiring: "언급 없음", hiringLevel: "neutral",
      hiringDetail: "설명회에서 인턴·정규직 채용 연계는 별도로 언급하지 않았습니다.",
      risk: "상관관계를 인과로 과장하지 않도록 시간분할 검증과 실제 편성자의 판단 비교가 필요합니다.",
    }),
  },
  {
    id: "cosliger", company: "코스리거", title: "화장품 ODM 트렌드·처방 제안 AI",
    scores: { finance: 59, backoffice: 73, strategy: 80, accounting: 58, hr: 62 },
    keywords: ["ODM", "트렌드 데이터", "특허", "처방", "고객 제안"],
    strength: "외부 트렌드와 사내 특허·처방을 묶어 고객 제안 리드타임을 줄이는 신생기업의 핵심 업무를 경험합니다.",
    caution: "내부 처방·특허의 공개 범위, 멘토링 주기, 성과평가 방식이 아직 구체적이지 않습니다.",
    briefing: briefing({
      stage: "신사업 PoC", stageLevel: "pilot",
      scope: "Trendier AI Pro의 외부 트렌드와 사내 특허·처방·원료를 결합해 ODM 초기 고객 제안을 생성합니다.",
      data: "회사가 Trendier Pro 계정과 내부 특허·처방 데이터를 제공할 계획입니다. 영업기밀 마스킹 조건이 필요합니다.",
      mentoring: "경력 있는 R&D 인력이 약 20명 있으나 데이터·AI 기술 멘토링 체계는 추가 확인이 필요합니다.",
      workstyle: "2024년 12월 설립된 신생 ODM 회사로 빠른 실무 적용이 기대되지만 근무·지원 조건은 미확정입니다.",
      portfolio: "공개 범위 미정", portfolioLevel: "warn",
      portfolioDetail: "처방·특허 원문은 영업기밀일 수 있어 익명 사례와 업무흐름 중심 공개안을 먼저 승인받아야 합니다.",
      hiring: "채용 검토", hiringLevel: "good",
      hiringDetail: "완료 후 채용 가능성을 검토하고 별도 보상도 협의할 수 있다고 언급했지만 확정 조건은 아닙니다.",
      risk: "외부 유료 서비스의 기능을 반복 개발하지 말고 내부 지식 결합과 제안 품질 검증에 집중해야 합니다.",
    }),
  },
  {
    id: "mnb", company: "엠엔비", title: "한·일 캐릭터 IP 트렌드 인텔리전스",
    scores: { finance: 54, backoffice: 63, strategy: 76, accounting: 50, hr: 59 },
    keywords: ["IP 비즈니스", "한·일 트렌드", "소셜 데이터", "대시보드", "추천"],
    strength: "넷마블 계열 IP 비즈니스에서 내부 성과와 외부 트렌드를 연결해 실제 기획 의사결정을 지원합니다.",
    caution: "회사의 AI 전문성이 깊지 않고 범위가 열려 있어 학생이 문제정의와 기술 선택을 주도해야 합니다.",
    briefing: briefing({
      stage: "공동 기획 PoC", stageLevel: "pilot",
      scope: "자사 채널 성과와 한·일 소셜·커뮤니티·뉴스·검색 신호를 모아 콘텐츠·사업 기획 인사이트를 추천합니다.",
      data: "개인정보를 제거한 채널 성과와 매출·이익·기획평가 자료, 외부 API 데이터를 제공할 수 있다고 설명했습니다.",
      mentoring: "실무자가 가까이 협업하고 빠르게 결과를 적용·피드백합니다. 다만 사내 AI 전문가가 많지는 않습니다.",
      workstyle: "2–3명, 기본적으로 매일 현장 근무를 기대합니다. 일본어는 필수가 아니며 한국부터 시작할 수 있습니다.",
      portfolio: "실무형 결과물 지향", portfolioLevel: "good",
      portfolioDetail: "좋은 실무 포트폴리오를 목표로 한다고 밝혔습니다. 실제 수치·IP 이미지의 공개 승인 범위는 별도 확인해야 합니다.",
      hiring: "언급 없음", hiringLevel: "neutral",
      hiringDetail: "설명회에서 직접적인 채용 연계는 언급되지 않았습니다.",
      risk: "데이터 수집, 분석, 추천, 대시보드를 한 번에 하려면 과도합니다. 의사결정 1개와 핵심 채널부터 시작해야 합니다.",
    }),
  },
  {
    id: "aurora-digital", company: "오로라월드", title: "AI 디지털 샘플링·패턴/BOM 자동화",
    scores: { finance: 45, backoffice: 62, strategy: 70, accounting: 43, hr: 50 },
    keywords: ["디지털 샘플", "2D→3D", "패턴", "BOM", "리드타임"],
    strength: "실제 샘플 제작 횟수와 소재·리드타임을 줄이는 제조 혁신 효과를 수치로 검증할 수 있습니다.",
    caution: "컴퓨터비전·3D·패턴 생성 범위가 넓고 현재 희망하는 금융·백오피스 직무와의 거리가 큽니다.",
    briefing: briefing({
      stage: "기존 PoC 고도화", stageLevel: "live",
      scope: "2D 아트워크를 AI 이미지·3D 모델·패턴·BOM으로 연결해 물리 샘플 반복을 줄이는 디지털 샘플링입니다.",
      data: "사내 디자인·패턴·BOM과 기존 PoC 결과를 사용하고 실제 제작 결과로 품질을 검증합니다.",
      mentoring: "관련 사내 3개 팀과 협업하며 실제 업무 흐름과 결과 검증을 받을 수 있습니다.",
      workstyle: "프로젝트당 최소 3명 정도를 선호합니다. 세부 지원 혜택은 설명회 시점에 미확정이었습니다.",
      portfolio: "승인 범위 확인", portfolioLevel: "warn",
      portfolioDetail: "캐릭터 디자인·패턴·BOM의 IP 보호 범위를 확인하고 생성 파이프라인과 정량 검증 위주로 공개해야 합니다.",
      hiring: "언급 없음", hiringLevel: "neutral",
      hiringDetail: "설명회에서 직접 채용 연계는 확인되지 않았습니다.",
      risk: "3개월에는 전 과정을 완전 자동화하기보다 샘플 횟수·시간을 줄이는 한 구간을 선택하는 편이 안전합니다.",
    }),
  },
  {
    id: "jido-labs", company: "지도랩스", title: "외국인 정착·비자·채용 AI 플랫폼",
    scores: { finance: 56, backoffice: 73, strategy: 82, accounting: 46, hr: 90 },
    keywords: ["비자 규정", "RAG", "채용 매칭", "AI 면접", "다국어"],
    strength: "비자·취업·정착 규칙과 채용 매칭을 연결해 HR·총무·글로벌 모빌리티 포트폴리오를 만들 수 있습니다.",
    caution: "기존 회사의 확정 과제가 아니라 내년 창업을 준비하는 아이디어여서 사업·조직·데이터 지속성 위험이 가장 큽니다.",
    briefing: briefing({
      stage: "창업 준비 아이디어", stageLevel: "startup",
      scope: "외국인의 비자·유학·취업·정착 전 과정을 규정 RAG, 맞춤 일자리·비자 매칭, AI 면접, 커뮤니티로 지원합니다.",
      data: "비자·규정·채용 공개정보를 수집해 출처가 보이는 다국어 답변과 규정 변경 에이전트를 만드는 구상입니다.",
      mentoring: "창업 제안자와 15년 경력의 기술 파트너가 스타트업 팀처럼 데이터·백엔드·프론트엔드를 멘토링할 계획입니다.",
      workstyle: "확정 법인·사무실·지원제도는 없습니다. 향후 6–8명 팀과 정부과제·임팩트 투자 유치를 구상 중입니다.",
      portfolio: "제품 공개 가능성 높음", portfolioLevel: "good",
      portfolioDetail: "공개 규정 기반 제품이라 기술 포트폴리오에는 유리하지만, 제3자 채용정보·개인정보 처리 기준은 설계해야 합니다.",
      hiring: "창업팀 가능성", hiringLevel: "warn",
      hiringDetail: "향후 국가별 외국인 인력 등을 채용할 구상은 있으나 현재 확정된 회사 채용 조건은 아닙니다.",
      risk: "‘기업 캡스톤’으로서의 실재성은 가장 낮습니다. 법인·책임자·데이터·IP·3개월 종료 후 운영주체를 서면 확인해야 합니다.",
    }),
  },
];

export const roleTrends = [
  ["자산운용", 160], ["IT", 98], ["대체투자", 78], ["주식", 65],
  ["데이터", 57], ["마케팅", 50], ["경영지원", 45], ["리서치", 40],
  ["AI", 39], ["회계", 37], ["리스크", 34], ["준법감시", 28],
];

export const portfolioPhases = [
  ["1–2주", "범위·권리", "사용자·KPI와 함께 데이터 접근, 공개 가능 범위, 수료·채용 조건을 서면으로 정합니다."],
  ["3–4주", "데이터 기반", "수집·정제·표준화와 품질검사 파이프라인을 만들고 베이스라인을 고정합니다."],
  ["5–7주", "모델·자동화", "모델 또는 업무자동화 흐름을 실제 사용자의 의사결정 단계에 맞춰 구현합니다."],
  ["8–9주", "현업 검증", "시간분할, 정답셋, 오류유형과 시간·비용·마진 등 업무효과를 함께 측정합니다."],
  ["10주", "통제", "권한, 민감정보, 승인, 감사로그와 실패모드를 설계하고 공개용 데이터를 분리합니다."],
  ["11–12주", "이중 산출물", "회사 실사용본과 익명화 포트폴리오본을 나눠 데모·보고서·README를 완성합니다."],
];
